import { z } from 'zod';

export const emitBusinessEventSchema = z.object({
  eventName: z.enum([
    'LOGIN_SUCCESS',
    'LOGIN_FAILED',
    'LOGOUT',
    'USER_CREATED',
    'USER_UPDATED',
    'USER_STATUS_CHANGED',
    'USER_DELETED',
    'PASSWORD_CHANGED',
    'PASSWORD_CHANGE_FAILED',
    'PASSWORD_RESET_REQUESTED',
    'PASSWORD_RESET_COMPLETED',
    'PRODUCT_CREATED',
    'PRODUCT_UPDATED',
    'PRODUCT_STATUS_CHANGED',
    'PRODUCT_DELETED',
    'SALES_ORDER_CREATED',
    'SALES_ORDER_UPDATED',
    'SALES_ORDER_CONFIRMED',
    'SALES_ORDER_CANCELLED',
    'SALES_ORDER_COMPLETED',
    'SALES_ORDER_DELETED',
    'SALES_DELIVERY_CREATED',
    'SALES_DELIVERY_SHIPPED',
    'SALES_DELIVERY_CANCELLED',
    'PURCHASE_ORDER_CREATED',
    'PURCHASE_ORDER_UPDATED',
    'PURCHASE_ORDER_SUBMITTED',
    'PURCHASE_ORDER_APPROVED',
    'PURCHASE_ORDER_ORDERED',
    'PURCHASE_ORDER_PARTIALLY_RECEIVED',
    'PURCHASE_ORDER_RECEIVED',
    'PURCHASE_ORDER_COMPLETED',
    'PURCHASE_ORDER_CANCELLED',
    'PURCHASE_ORDER_DELETED',
    'PURCHASE_RECEIPT_CREATED',
    'PURCHASE_RECEIPT_POSTED',
    'PURCHASE_RECEIPT_CANCELLED',
    'SUPPLIER_INVOICE_CREATED',
    'SUPPLIER_INVOICE_UPDATED',
    'SUPPLIER_INVOICE_POSTED',
    'SUPPLIER_INVOICE_CANCELLED',
    'SUPPLIER_PAYMENT_RECORDED',
    'INVENTORY_CREATED',
    'INVENTORY_UPDATED',
    'INVENTORY_ADJUSTED',
    'INVENTORY_DELETED',
    'INVENTORY_RESERVED',
    'INVENTORY_RESERVATION_RELEASED',
    'INVENTORY_RESERVATION_CONSUMED',
    'INVENTORY_STOCK_INCREASED',
    'INVENTORY_STOCK_DECREASED',
    'BOM_CREATED',
    'BOM_UPDATED',
    'BOM_COMPONENT_ADDED',
    'BOM_COMPONENT_UPDATED',
    'BOM_COMPONENT_REMOVED',
    'BOM_ACTIVATED',
    'BOM_DEACTIVATED',
    'BOM_ARCHIVED',
    'BOM_DELETED',
    'BOM_REVISION_CREATED',
    'BOM_VERSION_CREATED',
    'BOM_DEFAULT_SET',
    'MANUFACTURING_ORDER_CREATED',
    'MANUFACTURING_ORDER_UPDATED',
    'MANUFACTURING_ORDER_CONFIRMED',
    'MANUFACTURING_ORDER_PLANNED',
    'MANUFACTURING_ORDER_RELEASED',
    'MANUFACTURING_ORDER_STARTED',
    'MANUFACTURING_STARTED',
    'MANUFACTURING_ORDER_CANCELLED',
    'MANUFACTURING_CANCELLED',
    'MANUFACTURING_ORDER_COMPLETED',
    'MANUFACTURING_COMPLETED',
    'MANUFACTURING_ORDER_DELETED',
    'MANUFACTURING_MATERIAL_CONSUMED',
    'MANUFACTURING_CONSUMPTION_REVERSED',
    'MANUFACTURING_PRODUCTION_RECORDED',
    'MANUFACTURING_PRODUCTION_REPORTED',
    'MANUFACTURING_PRODUCTION_REVERSED',
    'AUDIT_EXPORTED',
  ]),
  organization_id: z.string().uuid({ message: 'Invalid organization ID format' }),
  user_id: z.string().uuid({ message: 'Invalid user ID format' }).nullable().optional(),
  actor_id: z.string().uuid({ message: 'Invalid actor ID format' }).nullable().optional(),
  entity_type: z.string().optional(),
  entity_id: z.string().nullable().optional(),
  request_id: z.string().nullable().optional(),
  correlation_id: z.string().nullable().optional(),
  reason: z.string().nullable().optional(),
  before_snapshot: z.record(z.unknown()).nullable().optional(),
  after_snapshot: z.record(z.unknown()).nullable().optional(),
  before: z.record(z.unknown()).nullable().optional(),
  after: z.record(z.unknown()).nullable().optional(),
  metadata: z.record(z.unknown()).optional(),
});
