-- UP
ALTER TABLE products ADD COLUMN IF NOT EXISTS price NUMERIC(19, 4) NOT NULL DEFAULT 0.0000 CHECK (price >= 0);
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost NUMERIC(19, 4) NOT NULL DEFAULT 0.0000 CHECK (cost >= 0);
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(19, 6) NOT NULL DEFAULT 0.000000 CHECK (tax_rate >= 0);

-- DOWN
ALTER TABLE products DROP COLUMN IF EXISTS tax_rate;
ALTER TABLE products DROP COLUMN IF EXISTS cost;
ALTER TABLE products DROP COLUMN IF EXISTS price;
