import { BaseQueryParams } from '@/types/api';

export const queryKeys = {
  users: {
    all: ['users'] as const,
    lists: () => [...queryKeys.users.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.users.lists(), params] as const,
    details: () => [...queryKeys.users.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.users.details(), id] as const,
  },
  partners: {
    all: ['partners'] as const,
    lists: () => [...queryKeys.partners.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.partners.lists(), params] as const,
    details: () => [...queryKeys.partners.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.partners.details(), id] as const,
  },
  products: {
    all: ['products'] as const,
    lists: () => [...queryKeys.products.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.products.lists(), params] as const,
    details: () => [...queryKeys.products.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.products.details(), id] as const,
  },
  warehouses: {
    all: ['warehouses'] as const,
    lists: () => [...queryKeys.warehouses.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.warehouses.lists(), params] as const,
    details: () => [...queryKeys.warehouses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.warehouses.details(), id] as const,
  },
  inventory: {
    all: ['inventory'] as const,
    lists: () => [...queryKeys.inventory.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.inventory.lists(), params] as const,
    details: () => [...queryKeys.inventory.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.inventory.details(), id] as const,
  },
  purchaseOrders: {
    all: ['purchase-orders'] as const,
    lists: () => [...queryKeys.purchaseOrders.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.purchaseOrders.lists(), params] as const,
    details: () => [...queryKeys.purchaseOrders.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.purchaseOrders.details(), id] as const,
  },
  salesOrders: {
    all: ['sales-orders'] as const,
    lists: () => [...queryKeys.salesOrders.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.salesOrders.lists(), params] as const,
    details: () => [...queryKeys.salesOrders.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.salesOrders.details(), id] as const,
  },
  manufacturing: {
    all: ['manufacturing'] as const,
    lists: () => [...queryKeys.manufacturing.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.manufacturing.lists(), params] as const,
    details: () => [...queryKeys.manufacturing.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.manufacturing.details(), id] as const,
  },
  audit: {
    all: ['audit'] as const,
    lists: () => [...queryKeys.audit.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.audit.lists(), params] as const,
    details: () => [...queryKeys.audit.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.audit.details(), id] as const,
    stats: (params?: BaseQueryParams) => [...queryKeys.audit.all, 'stats', params] as const,
    events: () => [...queryKeys.audit.all, 'events'] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    lists: () => [...queryKeys.notifications.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.notifications.lists(), params] as const,
  },
  stockLedger: {
    all: ['stock-ledger'] as const,
    lists: () => [...queryKeys.stockLedger.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.stockLedger.lists(), params] as const,
    details: () => [...queryKeys.stockLedger.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.stockLedger.details(), id] as const,
  },
  salesDeliveries: {
    all: ['sales-deliveries'] as const,
    lists: () => [...queryKeys.salesDeliveries.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.salesDeliveries.lists(), params] as const,
    details: () => [...queryKeys.salesDeliveries.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.salesDeliveries.details(), id] as const,
  },
  purchaseReceipts: {
    all: ['purchase-receipts'] as const,
    lists: () => [...queryKeys.purchaseReceipts.all, 'list'] as const,
    list: (params?: BaseQueryParams) => [...queryKeys.purchaseReceipts.lists(), params] as const,
    details: () => [...queryKeys.purchaseReceipts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.purchaseReceipts.details(), id] as const,
  },
} as const;
